<?php

function simrbase_tools_form_alter(&$form, &$form_state, $form_id) {
  //$simrbase_tools_form->hookForm();
 //  if ($form_id == 'views_exposed_form' && $form['#action'] == '/search/rosetta-stone-transcript-mapper') {
 //dpm($form);
 if ($form['#id'] == 'views-exposed-form-rosetta-stone-transcript-mapper-page'){


    $form['SIMRbase_uniquename']['#type'] = 'textarea';
    $form['other_uniquename']['#type'] = 'textarea';
    $names = array('other_uniquename','SIMRbase_uniquename');
    foreach ($names as $key){
        if (array_key_exists($key, $form_state['input']) and !is_null($form_state['input'][$key])){
	  $form_state['input'][$key] = preg_replace('/[\s,]+/',' ',trim($form_state['input'][$key]));
	}
     }
     $sql = 'SELECT name,description from chado.db where db_id in (select distinct other_db_id from chado.rosetta_stone_transcript_mapper ) order by description ASC';
     $results = db_query($sql);
     $form['other_db_name']['#options']=NULL;
     $form['other_db_name']['#options']['All']='- Any -';
//     $form['other_db_name']['#default_value']['0']='All'; // want to set default selected value, but i cnt get it to work
     foreach ($results as $r){
        $form['other_db_name']['#options'][$r->name] = $r->description;
    }

  }elseif($form['#id'] == 'views-exposed-form-t-page' or $form['#id'] == 'views-exposed-form-gene-search-by-loc-page'){
     if($form['#id'] == 'views-exposed-form-t-page'){
       $form['combine']['#type'] = 'textarea';
     }
     global $user;
     $gids = $user->roles;
//dpm($gids,'gids');
     $gid_str  = implode("','", $gids);
     $gid_str = "'".$gid_str."'";
//dpm($gid_str,'str');
     $sql = 'SELECT distinct common_name from chado.organism o, chado_organism co , node_access na , role r where o.organism_id = co.organism_id and co.nid = na.nid and o.organism_id in (select distinct organism_id from chado.chado_search_gene_search) and na.gid = r.rid and  r.name in ( '. $gid_str . '  ) order by common_name ASC';

    $results = db_query($sql);
     $form['common_name']['#options']=NULL;
     $form['common_name']['#options']['All']='- Any -';
     foreach ($results as $r){
        $form['common_name']['#options'][$r->common_name] = $r->common_name;
    }


    $sql_analysis = "SELECT distinct analysis from chado.chado_search_gene_search   
  where analysis similar to ( SELECT  '(' ||  string_agg(genus, '|') || ')%' as genus_list from chado.organism o, chado_organism co , node_access na , role r where o.organism_id = co.organism_id and co.nid = na.nid and o.organism_id in (select distinct organism_id from chado.chado_search_gene_search) and na.gid = r.rid and  r.name in (". $gid_str ." ) ) and analysis similar to (SELECT '%(' || string_agg(species, '|') || ')%' as species_list from chado.organism o, chado_organism co , node_access na , role r where o.organism_id = co.organism_id and co.nid = na.nid and o.organism_id in (select distinct organism_id from chado.chado_search_gene_search) and na.gid = r.rid and  r.name in (" . $gid_str . " )) order by analysis ASC";
    $results = db_query($sql_analysis);
    if($form['#id'] == 'views-exposed-form-t-page'){
       $form['name']['#options']=NULL;
       $form['name']['#options']['All']='- Any -';
       foreach ($results as $r){
        $form['name']['#options'][$r->analysis]= $r->analysis;
       }
     }elseif($form['#id'] == 'views-exposed-form-gene-search-by-loc-page'){
         $form['name_1']['#options']=NULL;
         $form['name_1']['#options']['All']='- Any -';
         foreach ($results as $r){
          $form['name_1']['#options'][$r->analysis]= $r->analysis;
         }
     }

  } // add in elseif for analysis.

  
 
  return $form;
}



?>
